### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by mckib2** [mckib2/rawdatarinator#3]
@michaelmendoza tried running `python readMeasDataVB15.py [data] -w` unsuccessfully.  It's hard to tell what's going on exactly because the versions of python and packages are unspecified in requirements.txt and the readme.  Also, dependencies rely on modules running when imported - not expected behavior from any production python code.  This means importing readMeasDataVB fails.  To remedy:

1) Show versions of python and third party packages used in requirements.txt and readme.md files
2) Make the software work on at least python 2.7 and 3.5
3) Make software work with importing readMeasDataVB15 and use a function call

**Comment by mckib2** [comment]
The data set in question appears to runs on my machine - the machine that raw-datar-inator was developed on.  So the inconsistencies must be that I do not specify versions.  Here is a screen shot of expected behavior:

![screenshot from 2018-03-01 19-46-56](https://user-images.githubusercontent.com/28734319/36881049-64ead270-1d89-11e8-8767-d8beba531f01.png)

**Comment by mckib2** [comment]
@michaelmendoza Does it work for you now on Windows using Python 2.7?

**Comment by michaelmendoza** [comment]
No, it doesn't work on Python 2.7 or 3.5 for me. I get different errors depending on the version of python i use

**Comment by mckib2** [comment]
I just got it installed on Windows 10 with Python 2.7.  Is this the error you get?

```
C:\Users\...\rawdatarinator>python readMeasDataVB15.py test-data/meas_MID66_TRUFI_STW_TE3_FID4922.dat
Traceback (most recent call last):
  File "readMeasDataVB15.py", line 644, in <module>
    decode_simple_opts(options,sys.argv[1:],readMeasDataVB15)
  File "C:\Users\emfaw\Documents\projects\rawdatarinator\decode_opts.py", line 31, in decode_simple_opts
    fun(args[0],**pargs)
  File "readMeasDataVB15.py", line 564, in readMeasDataVB15
    data['kSpace'][data['Acquisition'],data['Phase'],data['Repetition'],data['Echo'],data['Slice'],data['Channel'],data['Partition'],data['kSpace'].shape[7] - data['Nxr']:data['kSpace'].shape[7],data['Line']] = (temp[0::2] + 1j*temp[1::2]).astype(np.complex64)
ValueError: could not broadcast input array from shape (93) into shape (512)
```

**Comment by mckib2** [comment]
Just cloned onto a Windows 10 machine with fresh installations of both python 2.7 and 3.6 and everything appears to working as expected.  I'll close this issue for now.  Let me know if you're still getting errors.

**Comment by michaelmendoza** [comment]
Looks like it works now on my PC. Thanks!
