### ISSUE TITLE
Add package as a library in PIP

### ISSUE THREAD

**Issue by michaelmendoza** [mckib2/rawdatarinator#4]
I think it would be a good idea to add this package to python pip, so it would be easy to add to any python project! This would  make the rawdatarinator into a single-line install-able project. To do this, I recommend registering the project with PyPi, then we can use pip install rawdatarinator.

**Comment by mckib2** [comment]
@michaelmendoza Which license do we want to use?  Is GPL alright?

**Comment by michaelmendoza** [comment]
Sure, sounds good to me

**Comment by mckib2** [comment]
You can now do this with pip (python2.7) and pip3 (python3):
`pip install rawdatarinator`

and use it like this:
```
from rawdatarinator.readMeasDataVB15 import readMeasDataVB15 as rmd
data = rmd('raw.dat')
```

**Comment by michaelmendoza** [comment]
Sweet!
