### ISSUE TITLE
ValueError: read length must be positive or -1

### ISSUE THREAD

**Issue by soumickmj** [mckib2/rawdatarinator#5]
Hello.
I'm trying to use it in my python program. 
For testing, I wrote a simple python code:-

**_from rawdatarinator.readMeasDataVB15 import readMeasDataVB15 as rmd
file = 'D:\CloudData\OneDrive\OvGU\RawDat\coronal\meas_MID00123_FID00002_Nadelintervention_Coronal.dat'
data = rmd(file)_**

and this gives me the following error:-

File "C:\Users\schatter\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 6, in <module>
    data = rmd(file) #Read Raw Data - kSpace
  File "C:\Users\schatter\AppData\Local\conda\conda\envs\TestENV\lib\site-packages\rawdatarinator\readMeasDataVB15.py", line 139, in readMeasDataVB15
    xmlstr = infoParser.raw2xml(filename)
  File "C:\Users\schatter\AppData\Local\conda\conda\envs\TestENV\lib\site-packages\rawdatarinator\infoparser.py", line 193, in raw2xml
    info = cleanraw(filename)
  _**File "C:\Users\schatter\AppData\Local\conda\conda\envs\TestENV\lib\site-packages\rawdatarinator\cleanraw.py", line 8, in cleanraw
    info = f.read(num-4)
ValueError: read length must be positive or -1**_

I tried to run your python file from command prompt as well, 

python readMeasDataVB15.py raw.dat -w

This also returnd the same error.

Can you please let me know what is (could be ) the reason behind this and help me out with a solution?

Thanks.

**Comment by mckib2** [comment]
Sorry, just saw this.  I'll look into it!

**Comment by soumickmj** [comment]
yes

**Comment by mckib2** [comment]
Hmmm, is there a chance you could send me a copy of the raw data you're using?  It's hard for me tell what's going wrong without your input.  You could send a link to the file to nicholasbgp [at] gmail [dot] com

**Comment by mckib2** [comment]
Soumick has gotten me the file and I have replicated the issue.  It looks like the XProtocol parser used for VB15 is not robust enough moving forward, starting on a rewrite.

**Comment by mckib2** [comment]
Since this is for the old version of rawdatarinator, I'll close it.
